name = "Incremental Industry"
author = "monsh0"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a22b2a1ca1d18b537f96c8eefdb26be4c9f8a2adb8374282aaa0b998847f6f6d"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
