name = "Incremental Industry"
author = "monsh0"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1757fc56d1e9d02a36c6db5c977c22e13543a02d31e63ac80c9fa27ebd6cff1"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
