#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 02 15:36:37 IRST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=I Like Vanilla v1.4.3c.zip
